#!/usr/bin/env bash

python instructions.py > instructions.txt

clisp lisp/recipe-to-sexpr.lisp instructions.txt | clisp lisp/define-ca-number-concepts.lisp > lisp/ca-number-concepts.lisp

clisp lisp/recipe-to-sexpr.lisp instructions.txt
clisp lisp/recipe-to-sexpr.lisp instructions.txt | clisp lisp/do_instructions_ca.lisp
